export interface ImplementationTemplate {
  key: string;
  name: string;
  description: string;
  defaultDepartments: string[];
  permissionSetNames: string[];
  onboardingTasks: string[];
  checklistItems: string[];
  enabledModules: string[];
}

export const implementationTemplates: ImplementationTemplate[] = [
  {
    key: "small_business_payroll_only",
    name: "Small Business Payroll Only",
    description: "Ideal for small businesses running basic payroll with minimal HR needs.",
    defaultDepartments: ["Administration", "Operations"],
    permissionSetNames: ["Payroll Admin", "Employee Self-Service"],
    onboardingTasks: [
      "Configure company information",
      "Add employees",
      "Set up pay periods",
      "Configure taxes & deductions",
      "Run first payroll",
    ],
    checklistItems: [
      "Company information complete",
      "At least one employee added",
      "Pay period schedule configured",
      "Tax setup verified",
      "First payroll processed",
    ],
    enabledModules: ["payroll", "employees", "reports"],
  },
  {
    key: "payroll_time_tracking",
    name: "Payroll + Time Tracking",
    description: "Payroll with full time tracking, scheduling, and attendance management.",
    defaultDepartments: ["Administration", "Operations", "Warehouse"],
    permissionSetNames: ["Payroll Admin", "Time & Attendance Manager", "Employee Self-Service"],
    onboardingTasks: [
      "Configure company information",
      "Add employees",
      "Set up time tracking",
      "Configure scheduling",
      "Set up pay periods",
      "Configure taxes & deductions",
      "Run first payroll with time data",
    ],
    checklistItems: [
      "Company information complete",
      "Employees added with time tracking enabled",
      "Scheduling configured",
      "Time policies set up",
      "Pay period schedule configured",
      "Tax setup verified",
      "First payroll with hours processed",
    ],
    enabledModules: ["payroll", "employees", "time_tracking", "scheduling", "reports"],
  },
  {
    key: "full_hr_payroll_time",
    name: "Full HR + Payroll + Time",
    description: "Complete HR platform with payroll, time tracking, scheduling, and HR management.",
    defaultDepartments: ["Administration", "Human Resources", "Finance", "Operations", "Sales"],
    permissionSetNames: [
      "HR Admin",
      "Payroll Admin",
      "Time & Attendance Manager",
      "Manager",
      "Employee Self-Service",
    ],
    onboardingTasks: [
      "Configure company information",
      "Set up organizational hierarchy",
      "Add employees",
      "Configure HR policies",
      "Set up time tracking",
      "Configure scheduling",
      "Set up payroll and taxes",
      "Configure accruals",
      "Set up document management",
      "Run first full payroll",
    ],
    checklistItems: [
      "Company information complete",
      "Org hierarchy configured",
      "Employees added",
      "HR policies defined",
      "Time tracking enabled",
      "Scheduling configured",
      "Accruals set up",
      "Documents uploaded",
      "Tax setup verified",
      "First full payroll processed",
    ],
    enabledModules: [
      "payroll",
      "employees",
      "time_tracking",
      "scheduling",
      "hr",
      "documents",
      "reports",
      "accruals",
    ],
  },
  {
    key: "enterprise_multi_location",
    name: "Enterprise Multi-Location",
    description: "Enterprise-grade setup for organizations with multiple locations and complex org structures.",
    defaultDepartments: [
      "Corporate Administration",
      "Human Resources",
      "Finance",
      "Payroll",
      "Operations",
      "Sales",
      "IT",
      "Legal & Compliance",
    ],
    permissionSetNames: [
      "Enterprise Admin",
      "HR Admin",
      "Payroll Admin",
      "Location Manager",
      "Time & Attendance Manager",
      "Manager",
      "Employee Self-Service",
      "Auditor",
    ],
    onboardingTasks: [
      "Configure enterprise structure",
      "Set up legal entities",
      "Configure multiple locations",
      "Define org hierarchy",
      "Add employees across locations",
      "Configure role-based permissions",
      "Set up time tracking per location",
      "Configure payroll for all entities",
      "Set up document workflows",
      "Configure reports and analytics",
      "Compliance review",
      "Run first payroll across entities",
    ],
    checklistItems: [
      "Enterprise structure configured",
      "Legal entities set up",
      "All locations configured",
      "Org hierarchy complete",
      "Employees added across locations",
      "Role-based permissions configured",
      "Time tracking per location enabled",
      "Payroll for all entities configured",
      "Document workflows active",
      "Compliance review complete",
      "First enterprise payroll processed",
    ],
    enabledModules: [
      "payroll",
      "employees",
      "time_tracking",
      "scheduling",
      "hr",
      "documents",
      "reports",
      "accruals",
      "multi_location",
      "enterprise",
      "compliance",
    ],
  },
  {
    key: "staffing_contractor_heavy",
    name: "Staffing / Contractor-Heavy",
    description: "Optimized for staffing agencies and businesses with large contractor workforces.",
    defaultDepartments: ["Staffing Operations", "Contractor Relations", "Finance", "Compliance"],
    permissionSetNames: [
      "Staffing Admin",
      "Contractor Manager",
      "Payroll Admin",
      "Compliance Officer",
      "Contractor Self-Service",
    ],
    onboardingTasks: [
      "Configure company information",
      "Set up contractor classifications",
      "Add W-9 collection workflow",
      "Configure contractor pay types",
      "Set up invoice management",
      "Configure 1099 reporting",
      "Add contractors",
      "Set up time tracking for contractors",
      "Configure contractor payments",
      "Run first contractor payroll",
    ],
    checklistItems: [
      "Company information complete",
      "Contractor classifications configured",
      "W-9 collection workflow active",
      "Contractor pay types set up",
      "Invoice management configured",
      "1099 reporting configured",
      "Contractors added",
      "Time tracking enabled",
      "Contractor payment methods set up",
      "First contractor payroll processed",
    ],
    enabledModules: [
      "payroll",
      "employees",
      "contractors",
      "time_tracking",
      "documents",
      "reports",
      "invoicing",
      "compliance",
    ],
  },
];

export function getTemplate(key: string): ImplementationTemplate | undefined {
  return implementationTemplates.find((t) => t.key === key);
}
